name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name:  Checkout repository   $GITHUB_WORKSPACE
        uses:  actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install bats
        run: npm install -g bats
      - name: Run bats
        run: bats -v 
  job2:
    runs-on: ubuntu-latest
    steps: 
     - name: checkout repository
       uses: actions/checkout@v4
     - name: Install Node.js
       uses: actions/setup-node@v4
       with:
         node-version: lts/*
     - name: test bats
       run: npm test 
    needs: job1
   
  
        
