name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ env.NODE_VERSION}}
        - name:   priso 1
          run: node -v
        - name: interact with Github API
          on: 
            pull_request:
          jobs:
            create-issue:
              runs-on: ubuntu-latest
              steps:  
            
      
